theme: minima

title: "Any笔记"

author: Bin
email: laizebin9603@outlook.com

#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: >
  这是一个分享Web开发、编程技巧和技术趋势的个人博客。

