theme: minima

title: "Any笔记"
url: "https://noteany.blog"
baseurl: ""


author: Bin
email: laizebin9603@outlook.com

#
# The `>` after `description:` means to ignore line-breaks until next key. If
#   you wish to omit the line-break after the end of text, use `>-` instead.
description: >
  这是一个分享Web开发、编程技巧和技术趋势的个人博客。
  在这里，你可以找到关于现代开发工具、最佳实践和实用代码示例的文章。
  让我们一起踏上持续学习和技术探索的旅程。

# Google Analytics
google_analytics: G-62C6Y68JW8

# Exclude these files from navigation
exclude:
  - 404.md

# 是否显示文章摘要
show_excerpts: false

# 是否显示文章分类
show_categories: true


collections:

